### PR TITLE
Support IPv6 for outbound TCP interface (TCPClientInterface)

### PR DESCRIPTION
**Pull request by deavmi**
As per commit.

(Single line commit: BIG BRAIN :brain: )

---

Still haven't yet figured out the bind-side of things for the equivalent `TCPServerInterface` because I see the mention of class, rather than instance, variables and that seems sus to tamper with (I don't know Python, so I'd rather not)

### CODE REVIEW

**Comment by markqvist** [comment]
Awesome, I'll test this out and see if I can get the bind side working too.

**Comment by deavmi** [comment]
Great. Thanks Mark :)

On 05 September 2024 15:24:58 SAST, markqvist ***@***.***> wrote:
>Awesome, I'll test this out and see if I can get the bind side working too.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/markqvist/Reticulum/pull/545#issuecomment-2331678232
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Comment by deavmi** [comment]
If you need to setup a test you can just `sudo ifconfig eth0 2000::1/64` and `sudo ifconfig eth0 2001::2/64` and two machines respectively with both their `eth0` and `eth1` on the same ethernet segment.

**Comment by markqvist** [comment]
That's great, thanks for the hint!

**Comment by deavmi** [comment]
No problemo!

On 06 September 2024 16:53:34 SAST, markqvist ***@***.***> wrote:
>That's great, thanks for the hint!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/markqvist/Reticulum/pull/545#issuecomment-2334237913
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Comment by markqvist** [comment]
Yeah, on some Linux distros at least, it crashes interface initialisation, and Reticulum will permanently fail to bring up those interfaces. I'm looking into exactly what is going on, and also how to add IPv6 to the TCP server side. If you have any pointers, let me know!

> Perhaps a V6-variant would make sense, and could be done with minimal
code changes. i.e. just subclassing some the base TCP class and then manipulating
the constructors?

Yeah, that's not a bad idea. But if there is a universal way to easily add it within just the one interface, I think that's preferable, so let's try that out first.

**Comment by deavmi** [comment]
> Yeah, that's not a bad idea. But if there is a universal way to easily add it within just the one interface, I think that's preferable, so let's try that out first.

Agreed. Let me see what I can come up with.

**Comment by deavmi** [comment]
I do have a question. On the distros that it did work on, did it work as expected?

I am asking because maybe the way around this is to try figure out why it works
on some and not others and then see if during construction) there is a way
to determine that (maybe in `/proc/sys` somewhere) and do the v4-only connect
or the v4/v6 connect.

**Pull request merged**
