### PR TITLE
Add IPv6 support and enhance interface binding behavior

### PR DESCRIPTION
**Pull request by rlaneth**
### Overview

This PR introduces enhanced support for IPv6 and multiple IP addresses in the Reticulum networking stack, specifically:

#### `TCPServerInterface`

1. **Support for binding to multiple IP addresses,** including both IPv4 and IPv6. For example, `listen_ip = 0.0.0.0, ::0` allows listening on all IPv4 and IPv6 addresses simultaneously.
2. **Improved `device` option behavior** to bind to all addresses (IPv4 and IPv6) on the specified network interface, including the link-local IPv6 address. This resolves inconsistencies in the previous behavior, which only bound to the first IPv4 address on the given interface.

#### `TCPClientInterface`

1. **Enables connections to target hosts using IPv6 addresses** to ensure IPv6 compatibility for outbound TCP connections.

#### `UDPInterface`

⚠️ **Work in progress:** should be aligned with the enhanced `TCPServerInterface` and `TCPClientInterface` behavior, allowing for listening on and forwarding to multiple addresses, both IPv4 and IPv6.

#### Documentation

1. **Added examples of using IPv6 addresses and specifying multiple listening addresses** in the Reticulum documentation and example `rnsd` configuration file.

### Rationale

- **IPv6 support is aligned with Reticulum's goal for interfaceability,** and is critical as IPv4 address space becomes increasingly scarce. Many operators, including myself, are already transitioning to IPv6-only networks.
- **The current behavior of the `device` option is inconsistent with expectations.** Binding to a network device should intuitively bind to all associated IP addresses on that interface (both IPv4 and IPv6). The previous implementation only bound to the first IPv4 address, which causes issues with multi-address network interfaces, as is common in dual-stack or IPv6-only configurations. This PR corrects that behavior to improve usability and functionality.

### CODE REVIEW

**Comment by rlaneth** [comment]
I’ve created this draft PR to address the issues highlighted in [this comment](https://github.com/markqvist/Reticulum/pull/601#issuecomment-2481845547).

Since this is a substantial change, I want to ensure there’s ample time for feedback and testing from all interested parties, particularly @deavmi, @gretel, and @markqvist.

So far, I’ve tested the changes, and all TCP functionality appears to be working as expected. However, additional feedback and testing from others would be highly valuable. Next, I’ll focus on implementing the changes for the UDP interface.

**Comment by deavmi** [comment]
See PR #600 regarding `TCPClientInterface`.

On 20 November 2024 16:09:10 SAST, Rodrigo Laneth ***@***.***> wrote:
>I’ve created this draft PR to address the issues highlighted in [this comment](https://github.com/markqvist/Reticulum/pull/601#issuecomment-2481845547).
>
>Since this is a substantial change, I want to ensure there’s ample time for feedback and testing from all interested parties, particularly @deavmi, @gretel, and @markqvist.
>
>So far, I’ve tested the changes, and all TCP functionality appears to be working as expected. However, additional feedback and testing from others would be highly valuable. Next, I’ll focus on implementing the changes for the UDP interface.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/markqvist/Reticulum/pull/619#issuecomment-2488682637
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Comment by markqvist** [comment]
It seems this PR accidentially clashed with my own IPv6 binding work. For context, I started worked on the intreface modularity, hotplug and external interface module loading yesterday morning, but wanted to get @deavmi's IPv6 PRs mreged in first, since I misunderstood the PR comments, and thought they were tested and ready for merge.

When I found they were not really functional yet, I thought I'd just get the IPv6 stuff implemented first thing anyway, since it's been a lacking and sore point for a while. As such I didn't really check anything else, and this PR went unnoticed until I had practically completed the implementation.

I really appreciate you work and initiative here @rlaneth, but since the IPv6 stuff is implemented now, and part of the codebase for the interface modularity work, I will keep going with that.

I'd also like to note that your idea of allowing a single RNS interface to bind to multiple IP-addresses, and potentially multiple physical devices is neat and useful, but for now, we will have to go with mapping single RNS interfaces to single bind IP-addresses (and thus single kernel devices), since allowing multiple will greatly complicate interface hotplug, kernel up/down events, physical interfaces disconnecting/reconnecting etc.

The functionality will certainly be useful, but if anyone wants to work on it, it needs to be tested in all possible scenarios of kernel interfaces going up/down, disappearing/reappearing, and on all supported platforms (Linux, Android, macOS, Windows). From experience, getting all of that right takes a lot of time, and I don't currently have it, since focus is on getting interface modularity done right now.

**Comment by markqvist** [comment]
Also, since there is now IPv6 support for both client and server TCP interfaces in the master branch, I would hugely appreciate it if you can help testing out this in a variety of scenarios. I have limited IPv6 capable infrastructure available right now, so any help is appreciated.

Everything seems to work out fine over both link-local and wider networks, though. Tested with Yggdrasil as well, and that checks out.

**Comment by rlaneth** [comment]
@markqvist Thanks for the feedback and for implementing IPv6 support!

I understand the decision to keep single RNS interfaces bound to single IP addresses for now—it's clear that binding an interface to multiple addresses would be a major change and there'd be a lot to consider for such an implementation to work out well.

I’ll definitely be helping test out the current implementation in the master branch, as my interest in running Reticulum over IPv6 networks was what initially drove me to start working on it! 😉

**Comment by markqvist** [comment]
Awesome, thank you so much for that! Let me know if you encounter anything that's not acting as expected.

**Comment by deavmi** [comment]
> I’ll definitely be helping test out the current implementation in the master branch, as my interest in running Reticulum over IPv6 networks was what initially drove me to start working on it! 😉

Amen brother, amen

**Comment by deavmi** [comment]
Noted

On 21 November 2024 18:48:33 SAST, markqvist ***@***.***> wrote:
>Awesome, thank you so much for that! Let me know if you encounter anything that's not acting as expected.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/markqvist/Reticulum/pull/619#issuecomment-2491756931
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Pull request closed without merging**
