### PR TITLE
Add a pinch of CI/CD (no CD yet)

### PR DESCRIPTION
**Pull request by deavmi**
Ditto

(Kinda wanted this as I intend on testing some tings my side)

### CODE REVIEW

**Comment by markqvist** [comment]
Very nice! Been wanting to do this forever, and you came to the rescue :)

**Comment by markqvist** [comment]
That's really cool, didn't know it was that capable. Expanding the test suite for better coverage is definitely on the wishlist, so if you enjoy this kind of thing, I'd say it's a job ripe for taking! :)

**Comment by deavmi** [comment]
Once the inspiration strikes I shall do so.

What I will need though is some commandline tool I can use to generate traffic on either ends of the emulated network.

Could be some tool to just send an LXMF message for example.

The assertion would be a basic one at first. Did A receive message B.

On 09 September 2024 15:26:15 SAST, markqvist ***@***.***> wrote:
>That's really cool, didn't know it was that capable. Expanding the test suite for better coverage is definitely on the wishlist, so if you enjoy this kind of thing, I'd say it's a job ripe for taking! :)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/markqvist/Reticulum/pull/544#issuecomment-2338123493
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Comment by markqvist** [comment]
I'll see what I can do for that for the next release!

**Comment by deavmi** [comment]
Great!

On 09 September 2024 16:03:05 SAST, markqvist ***@***.***> wrote:
>I'll see what I can do for that for the next release!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/markqvist/Reticulum/pull/544#issuecomment-2338215659
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Pull request merged**
