### PR TITLE
Add support for TECHO device

### PR DESCRIPTION
**Pull request by jeremybox**
I am writing the firmware for the LylyGo T-ECHO device in the CE repo.  This repo needs a few changes to support that.

### CODE REVIEW

**Comment by jeremybox** [comment]
I added some unnecessary changes during my debugging.  Cleaning up the PR before I mark it as ready.

**Comment by jeremybox** [comment]
Good to go for forthcoming T-Echo implementation.  I will do another PR allowing selecting it from the menu when that is complete.

**Review by jeremybox — COMMENTED** [review]
spoke with @jacobeva and this seems more in line with current usage

**Comment by markqvist** [comment]
Thanks! As it is now, the product and model codes are a little confused together, with the T-Echo being a single model, under the `PRODUCT_RAK4631` product code. I think this will become a bit confusing, since it doesn't follow the standard convention of the rest of the boards.

But anyway, I'll just merge it now, and restructure the model and product codes a bit so it fits. We'll also need to add a proper model code for the 433 MHz version of the T-Echo, so I'll do that too. You may need to update the model codes in the firmware (and please also add support for the 433 MHz version, if it's not already there).

**Comment by markqvist** [comment]
Ok, I've configured the following codes:

```
PRODUCT_TECHO  = 0x15    # The product identifier
MODEL_T4       = 0x16    # For 433 MHz version
MODEL_T9       = 0x17    # For 868/915/923 MHz version
```

You will probably need to update these in the firmware as well.

In this way, it shows up as its own product, and `rnodeconf` will be able to also display what frequency range model the device is, when you run commands like `rnodeconf --info`. It's also important to have the correct model distinction in the firmware, since it may need to use it to set different parameters for the different frequency range models of the SX1262/SX1268 modem.

**Comment by markqvist** [comment]
Also, I've activated the menu options for the T-Echo. I have a release of RNS coming up shortly, and I thought you'd want this to be in there as well, since there probably wont be any releases for a while after that. When the firmware is ready, it can just be uploaded to the github release, and `rnodeconf` will be able to download and install it.

**Pull request merged**
