### PR TITLE
Add user systemd service to manual

### PR DESCRIPTION
**Pull request by jschulthess**
Add user systemd unit to manual in order to do all in userspace

### CODE REVIEW

**Comment by jschulthess** [comment]
Thought it would be nice to do everything in user space, including systemd as user unit file.
This way no privileged linking to /usr/local/bin or editing in /etc/systemd/system/ is necessary.

**Comment by markqvist** [comment]
Brilliant! Thank you very much! I'll merge this shortly.

**Comment by jschulthess** [comment]
I'm using this setup for connecting to my server at present and it works nicely .

**Comment by markqvist** [comment]
Very nice! This way is actually much better than as a system wide setup, and I think it should be the default. Thanks a lot for providing it. I'll rearrange the section next time I go over the docs. Of course, you are also very welcome to do those changes as well, if you want :)

**Comment by faragher** [comment]
I am always happy for more options and do not object to any of this in the slightest, but as a networking stack, I'm not sure why you'd want it in user space when the daemon can simply be accessed by user-space programs. What am I missing?

**Comment by jschulthess** [comment]
I consider the fact that the Reticulum network stack runs in user space as a unique feature. Just because traditionally network stacks are implemented as kernel modules doesn't mean it has to be.
I'm starting work on integrating Reticulum as an option in Qortal (qortal.org). The Qortal core is also run as a regular user. This makes it a natural fit for Reticulum.

**Pull request merged**
